#ifndef PROTO_HARFBUZZ_H
#define PROTO_HARFBUZZ_H

/*
** This file was machine generated by idltool.py 54.8.
** Do not edit.
**
** Prototype/inline/pragma header file combo.
*/

#include <cairo.h>
#include <freetype/freetype.h>
#include <hb.h>
#include <hb-aat.h>
#include <hb-cairo.h>
#include <hb-subset.h>
#include <hb-subset-repacker.h>

/****************************************************************************/

#ifndef __NOLIBBASE__
 #ifndef __USE_BASETYPE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::Library * HarfbuzzBase;
  #else
   extern struct Library * HarfbuzzBase;
  #endif
 #else
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::HarfbuzzLibrary * HarfbuzzBase;
  #else
   extern struct HarfbuzzLibrary * HarfbuzzBase;
  #endif
 #endif /* __USE_BASETYPE__ */
#endif /* __NOLIBBASE__ */

/****************************************************************************/

#ifdef __amigaos4__
 #include <interfaces/harfbuzz.h>
 #ifdef __USE_INLINE__
  #include <inline4/harfbuzz.h>
 #endif /* __USE_INLINE__ */
 #ifndef CLIB_HARFBUZZ_PROTOS_H
  #define CLIB_HARFBUZZ_PROTOS_H 1
 #endif /* CLIB_HARFBUZZ_PROTOS_H */
 #ifndef __NOGLOBALIFACE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::HarfbuzzIFace * IHarfbuzz;
  #else
   extern struct HarfbuzzIFace * IHarfbuzz;
  #endif
 #endif /* __NOGLOBALIFACE__ */
#else /* __amigaos4__ */
 #ifndef CLIB_HARFBUZZ_PROTOS_H
  #include <clib/harfbuzz_protos.h>
 #endif /* CLIB_HARFBUZZ_PROTOS_H */
 #if defined(__GNUC__)
  #ifndef __PPC__
   #include <inline/harfbuzz.h>
  #else /* __PPC__ */
   #include <ppcinline/harfbuzz.h>
  #endif /* __PPC__ */
 #elif defined(__VBCC__)
  #ifndef __PPC__
   #include <inline/harfbuzz_protos.h>
  #endif /* __PPC__ */
 #else /* __GNUC__ */
  #include <pragmas/harfbuzz_pragmas.h>
 #endif /* __GNUC__ */
#endif /* __amigaos4__ */

/****************************************************************************/

#endif /* PROTO_HARFBUZZ_H */
